// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Qwerty.Vsix.Ambienter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAmbienterPackageString = "7392b1ca-4552-4836-b59d-403e892c2b40";
        public const string guidCreateAmbientsCmdSetString = "a82cd131-63da-4677-aecf-12d2f0f56981";
        public const string guidImagesString = "47af7e9f-3320-4502-81a6-368480c8e61c";
        public static Guid guidAmbienterPackage = new Guid(guidAmbienterPackageString);
        public static Guid guidCreateAmbientsCmdSet = new Guid(guidCreateAmbientsCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int AmbienterMenuGroup = 0x1020;
        public const int CreateAmbientsId = 0x0100;
        public const int pngAmbienter16 = 0x0001;
    }
}
