// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Qwerty.Vsix.Ambienter
{
    static class Vsix
    {
        public const string Id = "492371a3-b83c-450e-b48f-18f766cdb375";
        public const string Name = "Qwerty.Ambienter";
        public const string Description = @"Visual Studio Extention for setting up ambient environment for a project.";
        public const string Language = "en-US";
        public const string Version = "0.1.0.1";
        public const string Author = "Qwerty";
        public const string Tags = "";
    }
}
